name: Deploy Next.js App

on:
  workflow_run:
    workflows: ["Format and Lint Check"]
    types: [completed]
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4
      - name: Build Docker Image
        run: |
          docker build -t prasadnarkhedkar/nextjs-wordgame .
      - name: Login to Docker Hub
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Push Docker Image to Docker Hub
        run: |
          docker push prasadnarkhedkar/nextjs-wordgame:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull Docker Image from Docker Hub
        run: |
          docker pull prasadnarkhedkar/nextjs-wordgame:latest
      - name: Stop and Remove Docker Container
        run: |
          docker stop nextjs-wordgame-container || true
          docker rm nextjs-wordgame-container || true
      - name: Run Docker Container
        run: |
          docker run -d -p 3000:3000 \
            -e MONGODB_URI="${{ secrets.MONGODB_URI }}" \
            -e ACCESS_TOKEN_SECRET="${{ secrets.ACCESS_TOKEN_SECRET }}" \
            -e REFRESH_TOKEN_SECRET="${{ secrets.REFRESH_TOKEN_SECRET }}" \
            --name nextjs-wordgame-container prasadnarkhedkar/nextjs-wordgame:latest
